"""The collection path (collect.py, render.py, core/, fetchers/) must never
import numpy or scipy: the tremble-threshold table is generated by
tools/calibrate_threshold.py (which needs them) and vendored into
core/normalize.py precisely so the daily run never simulates anything — see
tests/test_threshold_table.py for the vendored table's own structure and
digest checks.

LINT, not gate: a source scan, not a property of the running instrument, so
it runs on push via ``unittest discover tests -p "lint_*.py"`` (ci.yml's
lint job) and is deliberately NOT part of daily.yml's pre-collect gate — a
convention violation here must never cost an irreplaceable collection day.
"""
import os
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import support


class TestCollectionPathHasNoSimulationDependency(unittest.TestCase):
    def test_no_collection_module_imports_numpy_or_scipy(self):
        # render.py runs after collection, not during it, but is scanned here too
        # as defense-in-depth.
        roots = ["collect.py", "render.py"]
        for d in ("core", "fetchers"):
            roots += [os.path.join(d, f) for f in os.listdir(os.path.join(ROOT, d))
                      if f.endswith(".py")]
        for rel in roots:
            src = support.read_text(os.path.join(ROOT, rel))
            with self.subTest(module=rel):
                self.assertNotIn("import numpy", src)
                self.assertNotIn("import scipy", src)


if __name__ == "__main__":
    unittest.main()
