"""The tremble-threshold table is generated by tools/calibrate_threshold.py and
vendored into core/normalize.py so the daily run never simulates anything. The
generator needs numpy/scipy, which must never enter the collection path, so the
gate checks the table's structure and a digest instead — a hand-edit that does
not flip a historical verdict would otherwise slip past replay as well."""
import hashlib
import json
import os
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from core import normalize

TABLE_SHA256 = "42aae22e669bcf98f4f56d923eb22bfa7a318152e20f9f7400be34c2f2411e11"


class TestThresholdTable(unittest.TestCase):
    def test_the_table_is_unchanged(self):
        blob = json.dumps({int(k): round(float(v), 6) for k, v in normalize._C_N.items()},
                          sort_keys=True)
        self.assertEqual(hashlib.sha256(blob.encode()).hexdigest(), TABLE_SHA256,
                         "the vendored table changed; re-run tools/calibrate_threshold.py "
                         "--check and update this digest deliberately")

    def test_the_bar_falls_as_evidence_grows(self):
        keys = sorted(int(k) for k in normalize._C_N)
        values = [normalize._C_N[k] for k in keys]
        self.assertEqual(values, sorted(values, reverse=True),
                         "a longer window may never require a HIGHER z to tremble")

    def test_the_full_window_matches_the_flat_threshold(self):
        self.assertAlmostEqual(normalize._C_N[max(normalize._C_N)], normalize.THRESHOLD, places=6)


class TestCollectionPathHasNoSimulationDependency(unittest.TestCase):
    def test_no_collection_module_imports_numpy_or_scipy(self):
        roots = ["collect.py", "render.py"]
        for d in ("core", "fetchers"):
            roots += [os.path.join(d, f) for f in os.listdir(os.path.join(ROOT, d))
                      if f.endswith(".py")]
        for rel in roots:
            src = open(os.path.join(ROOT, rel)).read()
            with self.subTest(module=rel):
                self.assertNotIn("import numpy", src)
                self.assertNotIn("import scipy", src)


if __name__ == "__main__":
    unittest.main()
