"""Robust per-line normalization for tremor.

Each line is normalized ON ITS OWN with a rolling robust z-score (median for the
centre, Rousseeuw-Croux Qn for the scale — both shrug off outliers far better
than mean + standard deviation). Lines are NEVER combined into a single doom
score — the only composite tremor reports is a COUNT of how many lines are
trembling on a given day.
"""
import statistics
from datetime import date, datetime, timedelta
from itertools import combinations

WINDOW = 90        # rolling baseline: the last 90 available readings
MAX_AGE_DAYS = 180  # calendar cap: slow sources must not build baselines across seasons
THRESHOLD = 3.0    # |z| above this counts as "trembling" AT A FULL WINDOW; see _C_N
MIN_POINTS = 10    # need at least this much clean history to judge honestly
DECYCLE_MIN = 70   # de-cycle a weekly-rhythm line only once the window is this deep

# A line reporting nothing can be in several very different states, and the
# instrument used to express all of them the same way: an empty z-score. That is
# how a strait closing went unnoticed for fifteen days — the only line watching
# it COULD NOT SCORE, and "cannot score" looked exactly like "calm". The state is
# now recorded as data on every row, not as prose inside source_note.
STATUS_SCORING = "scoring"      # enough clean history; a z was computed
STATUS_WARMING = "warming-up"   # fewer than MIN_POINTS unique observations yet
STATUS_STALE = "stale"          # the source republished an observation we hold
# No reading at all. TWO CAUSES, and the column does not yet separate them: the
# fetch failed, or the fetch SUCCEEDED and the fetcher refused what came back —
# IODA reporting every country it watches as dark, Yahoo quoting the two yuan
# legs six hours apart, Fingrid down and a 60-second Statnett max being the
# wrong quantity. Both are honest empties with a stated reason in source_note,
# but "the source was down" and "we declined to read this" are different facts
# and the record told them apart only in prose. The FIRST split lands in round 18
# (STABLE_SINCE 2026-08-17): a market closure — the onshore yuan simply not trading
# on a weekend — now writes ``closed`` (below) instead of dark. The rest of the
# ambiguity (a real outage vs a weekday declined read) still lives in ``dark``;
# do not read dark as "the source failed".
STATUS_DARK = "dark"
# Market closure, split from dark (round 18): a line whose underlying market is
# shut on weekends (WEEKEND_MARKET) and has no reading on a Sat/Sun is CLOSED, not
# failed — there is no observation to miss when the market is not open. It counts
# toward neither the dark nor the blind tally; weekday holidays stay dark.
STATUS_CLOSED = "closed"
STATUS_FLAT = "no-spread"       # history has no resolvable dispersion to judge against
# A line is BLIND when it holds a reading it cannot judge. Dark is not blindness
# (it is already reported loudly); staleness is not either (the observation was
# judged when it first arrived).
BLIND_STATUSES = (STATUS_WARMING, STATUS_FLAT)


# The tremble bar, by how many readings the verdict was built from.
# Generated by tools/calibrate_threshold.py (fixed seed, re-derivable; --check
# regenerates and compares). Every entry is the |z| at which a window of that
# size gives the SAME odds of a false tremble on a calm day as a full window
# always had: 0.3916%. Non-increasing by construction — more evidence never
# raises the bar.
_C_N = {
    10: 4.686,
    11: 4.680,
    12: 4.243,
    13: 4.210,
    14: 3.983,
    15: 3.937,
    16: 3.780,
    17: 3.757,
    18: 3.652,
    19: 3.623,
    20: 3.557,
    21: 3.520,
    22: 3.479,
    23: 3.449,
    24: 3.417,
    25: 3.387,
    26: 3.364,
    27: 3.335,
    28: 3.326,
    29: 3.299,
    30: 3.291,
    31: 3.264,
    32: 3.257,
    33: 3.237,
    34: 3.231,
    35: 3.211,
    36: 3.210,
    37: 3.189,
    38: 3.189,
    39: 3.172,
    40: 3.169,
    41: 3.154,
    42: 3.154,
    43: 3.139,
    44: 3.139,
    45: 3.128,
    46: 3.128,
    47: 3.115,
    48: 3.115,
    49: 3.103,
    50: 3.103,
    51: 3.095,
    52: 3.095,
    53: 3.085,
    54: 3.085,
    55: 3.076,
    56: 3.076,
    57: 3.069,
    58: 3.069,
    59: 3.062,
    60: 3.062,
    61: 3.055,
    62: 3.055,
    63: 3.050,
    64: 3.050,
    65: 3.043,
    66: 3.043,
    67: 3.039,
    68: 3.039,
    69: 3.033,
    70: 3.033,
    71: 3.027,
    72: 3.027,
    73: 3.024,
    74: 3.024,
    75: 3.020,
    76: 3.020,
    77: 3.015,
    78: 3.015,
    79: 3.013,
    80: 3.013,
    81: 3.008,
    82: 3.008,
    83: 3.005,
    84: 3.005,
    85: 3.002,
    86: 3.002,
    87: 3.000,
    88: 3.000,
    89: 3.000,
    90: 3.000,
}

_QN_C = 2.2219  # scales the Qn order statistic to a Gaussian standard deviation
# Rousseeuw-Croux finite-sample corrections; past n=9 the closed form takes over.
_QN_D = {2: 0.399, 3: 0.994, 4: 0.512, 5: 0.844,
         6: 0.611, 7: 0.857, 8: 0.669, 9: 0.872}


def _qn_factor(n):
    if n in _QN_D:
        return _QN_D[n]
    return n / (n + 1.4) if n % 2 else n / (n + 3.8)


def _qn(values):
    """Rousseeuw-Croux Qn: the k-th smallest pairwise absolute difference.

    Same 50% breakdown point as MAD, and it collapses to zero on the same
    windows (once n//2+1 readings are tied). What it buys is calibration on
    SHORT windows, which is what tremor actually runs on: MAD is biased narrow
    there — about 0.91 sigma at n=10, measured — and a narrow denominator
    inflates every z. Qn measures ~1.00 sigma at every n and carries roughly
    half MAD's sampling variance, so a |z|>3 rule means much closer to what it
    claims. Measured null exceedance of |z|>3 on iid Gaussian data:
    n=10 5.3% -> 2.7%, n=20 2.1% -> 1.2%, n=90 0.56% -> 0.36%. Still not the
    0.3% of a true 3-sigma rule at short n — no scale estimator can deliver
    that from ten points — but roughly half the false alarms for the same
    threshold, and better power at the same false-alarm rate.
    """
    n = len(values)
    if n < 2:
        return 0.0
    pairs = sorted(abs(a - b) for a, b in combinations(values, 2))
    h = n // 2 + 1
    return _QN_C * _qn_factor(n) * pairs[h * (h - 1) // 2 - 1]


def _scale_z(values, today, quantum=None):
    """z of ``today`` against a clean value list, or None if there's no spread.

    A window with no resolvable dispersion yields None: there is genuinely
    nothing to measure against, and saying so is the honest answer. This used to
    fall through to a median-centered RMS, which has a breakdown point of zero —
    on a near-flat integer window a single-unit move scored above 3 and raised a
    tremble out of one quantum of resolution.

    ``quantum`` is the line's measurement resolution — one country, one basis
    point — and floors the scale for a line whose readings are COUNTED rather
    than measured. Qn collapses to zero once about a quarter of the window's
    pairs tie, which on a small-integer line is not a tail risk but the certain
    outcome of any calm stretch: twelve quiet days of "1 country" is enough, and
    the very next day a hundred-and-sixty-country outage would score nothing at
    all. A window of identical integers does not have zero spread — it has
    spread finer than the instrument can see, which is a different statement,
    and one quantum is the honest floor for it. This invents no data: it
    declines to claim a precision the source never had. (Measured on the real
    record: the floor has never once bound — the smallest Qn ever used on the
    quantized lines is 1.610 — so it changes no verdict that has been written,
    only the ones that would otherwise have gone silent.)
    """
    scale = _qn(values)
    if quantum:
        scale = max(scale, float(quantum))
    if scale <= 0:
        return None
    return (today - statistics.median(values)) / scale


def _weekday(date_str):
    # fromisoformat, not strptime: measured 0.10us against 2.47us, and this is
    # called once per reading per de-cycled row — 94% of _decycled's cost before
    # the change. The dates in this record are always ISO.
    return date.fromisoformat(date_str).weekday()


def _age_capped(history, dates, cycle_dates, today_date, max_age_days):
    """``(history, cycle_dates)`` with entries older than ``max_age_days`` dropped.

    For slow/deduplicated sources, "the last 90 observations" could otherwise
    span seasons or regimes. The cap is judged on the ROW date — when the
    reading entered the record — while ``cycle_dates`` (the observation dates
    the weekly rhythm belongs to) rides along, so the z baseline and the weekday
    veto always judge against the same sample set.
    """
    if cycle_dates is None:
        cycle_dates = dates
    if not (dates is not None and today_date and max_age_days):
        return history, cycle_dates
    try:
        cutoff = (datetime.strptime(today_date, "%Y-%m-%d")
                  - timedelta(days=max_age_days)).strftime("%Y-%m-%d")
    except (ValueError, TypeError):
        return history, cycle_dates
    kept = [(v, c) for v, d, c in zip(history, dates, cycle_dates)
            if not d or d >= cutoff]
    return [v for v, _ in kept], [c for _, c in kept]


def _same_weekday(history, cycle_dates, today_cycle_date):
    """Values whose CYCLE date falls on ``today_cycle_date``'s weekday.

    The cycle date is the date the weekly rhythm belongs to — the OBSERVATION
    date, not the date the row was written. They differ for any lagged source:
    GDELT publishes the previous full UTC day, and the lag is not even constant,
    so bucketing by row date would de-cycle against the wrong weekday and smear
    the very rhythm the de-cycling exists to remove. For a live snapshot line
    the two are the same date and this is a distinction without a difference.
    """
    try:
        target = _weekday(today_cycle_date)
        return [v for v, d in zip(history, cycle_dates)
                if v is not None and d and _weekday(d) == target]
    except (ValueError, TypeError):
        return []


def _decycled(history, cycle_dates, today, today_cycle_date):
    """``(residuals, today_residual)`` with each weekday's own level removed.

    THE RHYTHM IS REMOVED FROM THE WINDOW, NOT CARVED OUT OF IT. A line with a
    weekly beat used to be judged against its own weekday only — a correct
    diagnosis with an expensive cure, because seven buckets out of ninety
    readings leaves about twenty-six, permanently, and twenty-six readings fake
    a tremble two and a half times as often as ninety do. That is the highest
    false-alarm regime the instrument has, locked in forever, on a line that
    feeds the headline.

    Subtracting each weekday's median from its own days answers the same
    question with the whole window: Sunday is compared to what Sundays do, and
    then judged against how much this line moves in general. Measured on
    flights' own offsets: same-weekday baselining runs a 2.30-2.67% false-alarm
    rate over the coming year against de-cycling's 1.10-1.20%, with five to
    nine points more power on a real four-sigma collapse and the same
    suppression of the routine weekend dip (0.70% vs 0.67%) that the whole
    mechanism exists for.

    It is gated at ``DECYCLE_MIN`` because fitting seven medians into a thin
    window eats the spread it is supposed to preserve: at three readings per
    weekday the false-alarm rate measures 18%, and it is still 2.7% at forty.
    Below the gate the caller keeps the plain pooled window and its range veto.
    """
    # One pass: each reading's weekday is computed once and carried, rather
    # than parsed again to build the residuals.
    try:
        dated = [(_weekday(when), value)
                 for value, when in zip(history, cycle_dates)
                 if value is not None and when]
        today_weekday = _weekday(today_cycle_date)
    except (ValueError, TypeError):
        return None, None
    if not dated:
        return None, None
    by_weekday = {}
    for weekday, value in dated:
        by_weekday.setdefault(weekday, []).append(value)
    grand = statistics.median([v for values in by_weekday.values() for v in values])
    offsets = {day: statistics.median(values) - grand
               for day, values in by_weekday.items()}
    if today_weekday not in offsets:  # today's weekday is absent from the window
        return None, None
    return ([value - offsets[weekday] for weekday, value in dated],
            today - offsets[today_weekday])


def robust_z(history, today, dates=None, today_date=None, weekday_cycle=False,
             window=WINDOW, min_points=MIN_POINTS, max_age_days=MAX_AGE_DAYS,
             cycle_dates=None, today_cycle_date=None, quantum=None,
             anchor=None, materiality=None, weekend_market=False):
    """``(z, status, n)`` for ``today`` against the trailing ``window`` of history.

    ``n`` is the number of readings the verdict was actually built from, which
    the threshold depends on — see ``threshold_for``.

    ``history`` is the list of prior raw values (oldest..newest) and may contain
    None for gaps; gaps are dropped, so the window is the last ``window``
    *available* readings (which can span more than ``window`` calendar days when
    a source has been down). ``z`` is None when there is not enough clean
    history — or no spread at all — to judge honestly, and ``status`` says WHICH
    of those it was. Returning None is deliberate: tremor would rather say "I
    can't tell yet" than fake a number, and naming the kind of "can't" is what
    stops an unscoreable line from reading exactly like a calm one.

    De-cycling: sampling at a fixed time of day already removes the diurnal
    cycle. For a line with a strong WEEKLY rhythm (e.g. flights, which dip every
    weekend), pass ``weekday_cycle=True`` with aligned ``dates`` and
    ``today_date``: once the window is deep enough (``DECYCLE_MIN``) each
    weekday's own level is measured from the window and removed, and the day is
    judged against the whole de-cycled window rather than against its own
    weekday alone — see ``_decycled``. Below that depth the plain pooled window
    is used and the caller's range veto guards the weekend dip. (The slow
    seasonal cycle is absorbed by the trailing window; true year-over-year
    de-seasonalization waits on a full year of history.)
    """
    if today is None:
        # A weekend with no reading on a line whose market shuts weekends is a
        # market CLOSURE, not a failure — deterministic from the date, so replay
        # reproduces it without any signal from the (long-gone) fetch.
        if weekend_market and today_date and _weekday(today_date) >= 5:
            return None, STATUS_CLOSED, 0
        return None, STATUS_DARK, 0
    if materiality:
        # Anchored scale-mode: a line whose "normal" is a DECLARED constant (a $1
        # peg, a $0 facility take-up), not a rolling window. On such a near-constant
        # series both rolling estimates are degenerate — the centre is always the
        # anchor, and the Qn is either tiny (hypersensitive: a peg's ordinary ~10bp
        # venue fuzz reads z>3) or exactly zero (blind: a facility at $0 most days),
        # the one wall stablecoin_peg and fed_srf_takeup both hit. A declared ANCHOR
        # + MATERIALITY replaces both estimates with the truth: z = (today - anchor)
        # / materiality, so 3*MATERIALITY IS the smallest material move. It reads
        # only `today`, never `history`, so it structurally cannot forward-fill a
        # gap — a missing reading already returned DARK one line above — and a
        # declared constant has no sampling wobble, so n=window routes classify to
        # the flat 3.0 bar via the unchanged threshold_for. This is the
        # absolute-anchor / fixed-scale corner of the same "normal is not the
        # rolling window" idea that level_layer (pinned) and drift_layer (year-ago)
        # occupy; the concept is shared, the code stays separate.
        assert quantum is None, "a line declares QUANTUM or MATERIALITY, never both"
        return (today - (anchor or 0.0)) / materiality, STATUS_SCORING, window
    history, cycle_dates = _age_capped(
        history, dates, cycle_dates, today_date, max_age_days)
    today_cycle_date = today_cycle_date or today_date
    decycling = (weekday_cycle and cycle_dates is not None
                 and today_cycle_date is not None)
    if decycling:
        # Pair once and take the values from the pairing, so the None-filter and
        # the trailing slice happen a single time on the path that needs both.
        paired = [(v, c) for v, c in zip(history, cycle_dates) if v is not None][-window:]
        values = [v for v, _ in paired]
    else:
        values = [v for v in history if v is not None][-window:]
    if len(values) < min_points:
        return None, STATUS_WARMING, len(values)

    if decycling and len(values) >= DECYCLE_MIN:
        residuals, today_residual = _decycled(
            values, [c for _, c in paired], today, today_cycle_date)
        if residuals is not None and len(residuals) >= min_points:
            z = _scale_z(residuals, today_residual, quantum=quantum)
            return ((z, STATUS_SCORING, len(residuals)) if z is not None
                    else (None, STATUS_FLAT, len(residuals)))

    z = _scale_z(values, today, quantum=quantum)
    return ((z, STATUS_SCORING, len(values)) if z is not None
            else (None, STATUS_FLAT, len(values)))


def threshold_for(n):
    """The |z| a window of ``n`` readings must exceed to count as trembling.

    One threshold cannot mean one thing. The z is today's distance from an
    ESTIMATED median in units of an ESTIMATED scale, and estimates from ten
    readings wobble in a way estimates from ninety do not — so the same |z| > 3
    fires on a calm day 2.62% of the time at n=10 and 0.391% at n=90, and both
    regimes are live on this record at once. The table below (generated by
    tools/calibrate_threshold.py, fixed seed, re-derivable) moves the bar so
    every line, at every age, has the SAME 0.391% odds of a false tremble on a
    calm day — the odds a full window always had, which is why nothing about a
    mature line changes.

    What this does NOT fix, and must not be sold as fixing: the excess tremble
    rate on the slow financial lines (5.5-8.5% of days against a 0.391% null)
    is about two-thirds SERIAL DEPENDENCE, not window size — an AR(1) null at
    credit_spread's own lag-1 of 0.987 already produces 4.7%. Those lines
    tremble in long real episodes, and the fix for reading them honestly is
    counting episodes rather than days (tools/episodes.py), not a threshold.
    """
    if n >= WINDOW:
        return THRESHOLD
    # The table covers MIN_POINTS..WINDOW exhaustively, and a shorter window
    # never reaches here — robust_z returns warming-up with no z, and classify
    # short-circuits on None. The floor is the bar for the thinnest window the
    # instrument will judge at all.
    return _C_N.get(n, _C_N[MIN_POINTS])


def classify(z, n=WINDOW):
    """Map a z-score (or None) to ``(trembling: int, direction: str)``."""
    if z is None:
        return 0, ""
    direction = "up" if z > 0 else ("down" if z < 0 else "flat")
    trembling = 1 if abs(z) > threshold_for(n) else 0
    return trembling, direction


def weekday_range_veto(history, dates, today, today_date,
                       min_samples=3, max_samples=MIN_POINTS, margin=0.05,
                       cycle_dates=None, today_cycle_date=None):
    """Warm-up veto for weekly-cycle lines, nonparametric by design.

    Until a line has ``max_samples`` same-weekday readings (when the proper
    weekday baseline engages in ``robust_z``), a full-window tremble can be a
    routine weekend dip read against a weekday-heavy window. With as few as
    ``min_samples`` same-weekday readings we can still ask a scale-free
    question: has this LEVEL been seen on this weekday before? If today lies
    inside the same-weekday [min, max] envelope (widened by ``margin`` of the
    span), the tremble is suppressed. No dispersion estimate is used — a
    genuine crisis value falls outside every previously seen same-weekday
    value and can never be vetoed.

    Returns ``(vetoed: bool, detail: str)``; detail is auditable and should be
    recorded wherever the suppression is applied.
    """
    if today is None or not dates or today_date is None:
        return False, ""
    # Same age cap as robust_z, so the veto judges against the same sample set
    # the z-score was computed from.
    history, cycle_dates = _age_capped(
        history, dates, cycle_dates, today_date, MAX_AGE_DAYS)
    same = _same_weekday(history, cycle_dates, today_cycle_date or today_date)
    n = len(same)
    if not (min_samples <= n < max_samples):
        return False, ""
    lo, hi = min(same), max(same)
    pad = (hi - lo) * margin
    if lo - pad <= today <= hi + pad:
        return True, (f"suppressed: within same-weekday range "
                      f"[{lo:g}, {hi:g}] (n={n})")
    return False, ""


def judge(history, dates, obs_dates, today, today_obs, today_date,
          weekly_cycle=False, quantum=None, anchor=None, materiality=None,
          weekend_market=False):
    """Today's verdict: ``(z, trembling, direction, note, status)``.

    Owns the whole scoring sequence in one place — observation dedup (lagged
    sources republish a reading until they update; only the first occurrence
    counts), the stale check (a republished observation scores no new z and
    raises no flag), the calendar cap, the weekday baseline, classification,
    and the weekly-cycle warm-up veto. ``note`` carries any verdict detail
    (stale marker, veto reason) for the row's source_note.

    ``history``/``dates``/``obs_dates`` are aligned per prior row; ``today_obs``
    is today's observation date ("" for real-time lines). ``status`` says WHY a
    reading was or was not judged, so that "cannot score" can never again be
    displayed identically to "calm".
    """
    values, kept_dates, kept_cycle = [], [], []
    seen_obs = set()
    for v, d, o in zip(history, dates, obs_dates):
        if o:
            if o in seen_obs:
                continue
            seen_obs.add(o)
        values.append(v)
        kept_dates.append(d)
        # A weekly rhythm belongs to the day the reading is ABOUT, so de-cycling
        # keys off the observation date when the source publishes one.
        kept_cycle.append(o or d)
    if today_obs and today_obs in seen_obs:
        return None, 0, "", "[stale: observation already recorded]", STATUS_STALE
    today_cycle = today_obs or today_date
    z, status, n = robust_z(
        values, today, dates=kept_dates, today_date=today_date,
        weekday_cycle=weekly_cycle,
        cycle_dates=kept_cycle, today_cycle_date=today_cycle, quantum=quantum,
        anchor=anchor, materiality=materiality, weekend_market=weekend_market)
    trembling, direction = classify(z, n)
    # The veto guards the weekend dip only in the pooled regime; once the window
    # is deep enough to have the rhythm removed outright, it has nothing to add.
    if trembling and weekly_cycle and n < DECYCLE_MIN:
        vetoed, detail = weekday_range_veto(
            values, kept_dates, today, today_date,
            cycle_dates=kept_cycle, today_cycle_date=today_cycle)
        if vetoed:
            return z, 0, direction, f"[{detail}]", status
    return z, trembling, direction, "", status
